### ISSUE TITLE
Variable in Alert Title

### ISSUE THREAD

**Issue by ngcoders** [baseapp/SwarmSense-IoT-Platform#14]
Like the Alert Text , We should be able to to add the variable name in the Email Alert Title.

This makes it easy to keep track when Emails arrive. 

Also Alert Text should be a text area.

**Comment by gopalkildoliya** [comment]
# Subtask
- [ ] Variables in Alerts Title
- [ ] Make **Alert Text** field to textbox in UI @aman1106

**Comment by aman1106** [comment]
@gopalkildoliya Changed alert text field to textbox and updated 'type' field in alert form to have "equal to" and "not equal to" options.

**Comment by gopalkildoliya** [comment]
Now you can use variables in alter title also, as you are using in the alert message. Use `{{ variable_name }}` format to add a variable in title. List of supported variable names is [here](https://github.com/baseapp/SwarmSense-IoT-Platform/wiki/Variables-in-alert-emails).
