### ISSUE TITLE
Sensor configuration page is not showing latest config

### ISSUE THREAD

**Issue by gopalkildoliya** [baseapp/SwarmSense-IoT-Platform#16]
While changing the configuration of a sensor, it shows the old values that were stored in the browser. It doesn't reflect the changes made by the other user.
![screenshot from 2018-12-04 18-16-56](https://user-images.githubusercontent.com/11576685/49443222-e078eb00-f7f1-11e8-9a3e-43c59f331f21.png)

On the configuration page, it should fetch the latest configuration from the server.

**Comment by aman1106** [comment]
@gopalkildoliya Resolved the issue.
