### ISSUE TITLE
Its not Working

### ISSUE THREAD

**Issue by untilbit** [baseapp/SwarmSense-IoT-Platform#2]
I have followd instructions but it's not working. Please update. Also folder release/script cannot be found

**Comment by gopalkildoliya** [comment]
Hi @untilbit , I am not sure which instructions you are following. Please use [README.md](https://github.com/baseapp/SwarmSense-IoT-Platform/blob/master/README.md) for setup instructions. 

Get the latest release file https://github.com/baseapp/SwarmSense-IoT-Platform/releases/download/v0.1.0-alpha/swarmsense.tar.gz . It has a `snms.zip` file which has all the required files for the setup.

We also have docker container based setup scripts, you can give it a try.

If still it's not working, please let me know.

**Comment by untilbit** [comment]
I have tried docker and when i run the command to create databse it's giving this error, because the configuration file, it's not a file but a folder:

> IsADirectoryError: [Errno 21] Is a directory: '/etc/snms.conf'

**Comment by untilbit** [comment]
Still in alpha state but looks promising, i'll check again in future versions.

**Comment by gopalkildoliya** [comment]
Thanks for feedback @untilbit .

**Comment by gopalkildoliya** [comment]
Closing the issue for now.
